config/routes.rb
EspnDb::Application.routes.draw do


  root to: 'si_headlines#index'
  resources :ncaa_mens_fb_headlines
  resources :ncaa_mens_bb_headlines
  resources :nhl_headlines
  resources :nfl_headlines
  resources :nba_headlines
  resources :headlines
  resources :mlb_headlines
  resources :si_headlines

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'contact_forms#new', as: 'contact_forms'
  post 'contact', to: 'contact_forms#create'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: [:get, :post]
end

app/models/headline.rb
class Headline < ActiveRecord::Base

	serialize :image_url

	def self.update_from_espn(espn_url)
		data = Faraday.get espn_url
		data = JSON.parse data.body
		feed = data['headlines']
		add_headlines(feed) 
	end

	private

	def self.add_headlines(feed)
		feed.each do |headline|
			headline.deep_symbolize_keys!
			#headline[:images].map { |m| m.symobilize_keys! }
			unless exists? :espn_id => headline[:id]
				create!(
					:espn_id 				=> headline[:id],
					:headline 			=> headline[:headline],
					:description		=> headline[:description],
					:last_modified 	=> headline[:lastModified],
					:href						=> headline[:links][:web][:href],
					:image_url => headline[:images].map { |m| m['url'] } 
					)
			end
		end
	end
end

#add 'sportId', 'teamId'


#http://api.espn.com/v1/sports/news/headlines/top?apikey=2tpfdnkmhnvnxkcr59nw8gmj
					# :sport_id 			=>  headline[:categories].first['sportId'],
					# :team_id				=>	headline[:categories].first['teamId'],

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController
  before_action :set_headline, only: [:show]

	def index
		@headlines = Headline.order('last_modified desc').page(params[:page]).per_page(60)
	end

	def show
	end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_headline
    @headline = Headline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def headline_params
    params.require(:headline).permit(:headline, :description)
  end
end
	

app/views/headlines/_headline.html.erb
<!-- <ul class="clearing-thumbs" data-clearing>
			<% @headlines.map do |headline| %>
				
				<% if headline.image_url.map.any? %>
				<li><a class="ttt th th-item"><%= image_tag headline.image_url.first, data: { caption: "<a href=#{headline_path(headline)}>#{headline.description}</a>" } %></a></li>

				<% else %>
					<li><a class="ttt th th-item"><%= image_tag('espn_logo_frozen.png', data: { caption: "<a href=#{headline_path(headline)}>#{headline.description}</a>" }) %></a></li>
				<% end %>
				<% end %>
			</ul> -->

app/views/headlines/index.html.erb
<h5>ESPN Headlines</h5>


		
		
		<ul class="clearing-thumbs" data-clearing>
		<% @headlines.map do |headline| %>
			
			<% if headline.image_url.map.any? %>
			<li><a class="ttt th th-item"><%= image_tag headline.image_url.first, data: { caption: "<a href=#{headline_path(headline)}>#{headline.description}</a>" } %></a></li>

			<% else %>
				<li><a class="ttt th th-item"><%= image_tag('espn_logo_frozen.png', data: { caption: "<a href=#{headline_path(headline)}>#{headline.description}</a>" }) %></a></li>
			<% end %>
			<% end %>
		</ul>
		
		


<div class="row">
	<div class="large-12 large-centered columns">
		<%= will_paginate @headlines %>
	</div>
</div>

app/views/headlines/index.js.erb
// $('#pin').prepend('<%= j render(@headlines) %>');
// <% if @headlines.next_page %>
// 	$('.pagination').replaceWith('<%= j will_paginate(@headlines) %>');
// <% else %>
// 	$('.pagination').remove();
// <% end %>
// <% sleep 1 %>

app/views/headlines/show.html.erb
<h5>ESPN Headlines</h5>
<div class="row">
	<div class="large-12 columns">
		<h6 class="show-headline-headline"><%= @headline.headline %></h6>
		<p class="show-headline-time"><%= @headline.last_modified.localtime.strftime('%l:%M %p %Z %-m-%d-%Y') %></p>
		<p class="show-headline-description"><%= @headline.description %></p>
		<p><%= link_to 'Full Story', @headline.href, target: "_blank" %></p>
		<% if @headline.image_url.map.any? %>
			<% @headline.image_url.map do |image| %>
		<%= image_tag image %>
		<% end %>
		<% else %>
			<p class="show-headline-image"><%= image_tag('espn_logo_frozen.png') %></p>
		<% end %>
		<p><%= link_to "Back", headlines_path %></p>
	</div>
</div>