config/routes.rb
EspnDb::Application.routes.draw do


  root to: 'si_headlines#index'
  resources :ncaa_mens_fb_headlines
  resources :ncaa_mens_bb_headlines
  resources :nhl_headlines
  resources :nfl_headlines
  resources :nba_headlines
  resources :headlines
  resources :mlb_headlines
  resources :si_headlines

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'contact_forms#new', as: 'contact_forms'
  post 'contact', to: 'contact_forms#create'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: [:get, :post]
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="large-12 large-centered columns">
			<dl class="sub-nav">
				<dd><%= link_to 'Sports Illustrated Headlines', root_path %></dd>
			  <dd><%= link_to 'ESPN Headlines', headlines_path %></dd>
			  <dd><%= link_to 'NFL', nfl_headlines_path %></dd>
			  <dd><%= link_to 'MLB', mlb_headlines_path %></dd>
			  <dd><%= link_to 'NBA', nba_headlines_path %></dd>
			  <dd><%= link_to 'NHL', nhl_headlines_path %></dd>
			  <dd><%= link_to 'NCAAF', ncaa_mens_fb_headlines_path %></dd>
			  <dd><%= link_to 'NCAAM', ncaa_mens_bb_headlines_path %></dd>
			</dl>
		</div>
	</div>
	<div class="row">
		<div class="large-12 large-centered columns">
			<dl class="sub-nav">
			  <dd><%= link_to 'About', about_path %></dd>
			  <dd><%= link_to 'Contact', contact_path %></dd>
			</dl>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% unless request.fullpath.include?('contact') || request.fullpath.include?('about') || params[:action] == 'show' %>
		<div id="turn-toggle-thumb">Toggle Thumbs</div>
	<% end %>
	<div class="row">
		<div class="large-12 large-centered columns">
			<dl class="sub-nav">
			  <dd><%= link_to 'Sports Illustrated Headlines', root_path %></dd>
			  <dd><%= link_to 'ESPN Headlines', headlines_path %></dd>
			  <dd><%= link_to 'NFL', nfl_headlines_path %></dd>
			  <dd><%= link_to 'MLB', mlb_headlines_path %></dd>
			  <dd><%= link_to 'NBA', nba_headlines_path %></dd>
			  <dd><%= link_to 'NHL', nhl_headlines_path %></dd>
			  <dd><%= link_to 'NCAAF', ncaa_mens_fb_headlines_path %></dd>
			  <dd><%= link_to 'NCAAM', ncaa_mens_bb_headlines_path %></dd>
			</dl>
		</div>
	</div>
</header>

app/views/layouts/_new_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
    	<% unless request.fullpath.include?('contact') || request.fullpath.include?('about') || params[:action] == 'show' %>
				<div id="turn-toggle-thumb">Toggle Thumbs</div>
			<% end %>
    </li>

    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>

  </ul>

	<section class="top-bar-section">
		<!-- Right Nav Section -->
    <ul class="right">
    	<li><%= link_to 'Sports Illustrated Headlines', root_path %></li>
		  <li><%= link_to 'ESPN Headlines', headlines_path %></li>
		  <li><%= link_to 'NFL', nfl_headlines_path %></li>
		  <li><%= link_to 'MLB', mlb_headlines_path %></li>
		  <li><%= link_to 'NBA', nba_headlines_path %></li>
		  <li><%= link_to 'NHL', nhl_headlines_path %></li>
		  <li><%= link_to 'NCAAF', ncaa_mens_fb_headlines_path %></li>
		  <li><%= link_to 'NCAAM', ncaa_mens_bb_headlines_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<title><%= content_for?(:title) ? yield(:title) : "Sports Headlines" %></title>
  	<%= stylesheet_link_tag    "application", media: "all" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/new_header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>