config/routes.rb
EspnDb::Application.routes.draw do


  root to: 'si_headlines#index'
  resources :ncaa_mens_fb_headlines
  resources :ncaa_mens_bb_headlines
  resources :nhl_headlines
  resources :nfl_headlines
  resources :nba_headlines
  resources :headlines
  resources :mlb_headlines
  resources :si_headlines

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'contact_forms#new', as: 'contact_forms'
  post 'contact', to: 'contact_forms#create'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: [:get, :post]
end

app/models/nfl_headline.rb
class NflHeadline < ActiveRecord::Base

	serialize :image_url

	def self.update_from_espn(espn_url)
		data = Faraday.get espn_url
		data = JSON.parse data.body
		feed = data['headlines']
		add_headlines(feed)
	end

	private

	def self.add_headlines(feed)
		feed.each do |headline|
			headline.deep_symbolize_keys!
			#headline[:images].map { |m| m.symobilize_keys! }
			unless exists? :espn_id => headline[:id]
				create!(
					:espn_id 				=> headline[:id],
					:headline 			=> headline[:headline],
					:description		=> headline[:description],
					:last_modified 	=> headline[:lastModified],
					:href						=> headline[:links][:web][:href],
					:image_url => headline[:images].map { |m| m['url'] }  
					)
			end
		end
	end
end


#http://api.espn.com/v1/sports/news/headlines/top?apikey=2tpfdnkmhnvnxkcr59nw8gmj

app/controllers/nfl_headlines_controller.rb
class NflHeadlinesController < ApplicationController
  before_action :set_nfl_headline, only: [:show]

	def index
		@nfl_headlines = NflHeadline.all.order('last_modified desc').page(params[:page]).per_page(60)
	end

	def show
	end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_nfl_headline
    @nfl_headline = NflHeadline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def nfl_headline_params
    params.require(:headline).permit(:headline, :description)
  end
end

app/helpers/nfl_headlines_helper.rb
module NflHeadlinesHelper
end

app/views/nfl_headlines/index.html.erb
<h5>ESPN NFL Headlines</h5>

	<ul class="clearing-thumbs" data-clearing>
	<% @nfl_headlines.map do |headline| %>
	
	<% if headline.image_url.map.any? %>
	<li><a class="ttt th th-item"><%= image_tag headline.image_url.first, data: { caption: "<a href=#{nfl_headline_path(headline)}>#{headline.description}</a>" } %></a></li>

	<% else %>
		<li><a class="ttt th th-item"><%= image_tag('espn_logo_frozen.png', data: { caption: "<a href=#{nfl_headline_path(headline)}>#{headline.description}</a>" }) %></a></li>
	<% end %>
	<% end %>
</ul>

<div class="row">
	<div class="large-12 large-centered columns">
		<%= will_paginate @nfl_headlines %>
	</div>
</div>

app/views/nfl_headlines/show.html.erb
<h5>ESPN NFL Headlines</h5>
<div class="row">
	<div class="large-12 columns">
		<h6 class="show-headline-headline"><%= @nfl_headline.headline %></h6>
		<p class="show-headline-time"><%= @nfl_headline.last_modified.localtime.strftime('%l:%M %p %Z %-m-%d-%Y') %></p>
		<p class="show-headline-description"><%= @nfl_headline.description %></p>
		<p><%= link_to 'Full Story', @nfl_headline.href, target: "_blank" %></p>
		<% if @nfl_headline.image_url.map.any? %>
			<% @nfl_headline.image_url.map do |image| %>
		<%= image_tag image %>
		<% end %>
		<% else %>
			<p class="show-headline-image"><%= image_tag('espn_logo_frozen.png') %></p>
		<% end %>
		<p><%= link_to "Back", nfl_headlines_path %></p>
	</div>
</div>